# Generated by Django 6.0.3 on 2026-04-06 18:19

import master_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('year', models.IntegerField(default=2026)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(2, 'Admin')], default=2)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', master_admin.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('totalUserAllocated', models.IntegerField(default=0)),
                ('totalAmount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('year', models.IntegerField(default=2026)),
                ('categories', models.ManyToManyField(to='master_admin.category')),
            ],
        ),
    ]
