# Generated by Django 6.0.3 on 2026-04-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_adhoc',
            field=models.BooleanField(default=False),
        ),
    ]
