# Generated by Django 6.0.3 on 2026-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_admin', '0002_event_is_adhoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'Admin')], default=2),
        ),
    ]
