# Generated by Django 6.0.3 on 2026-04-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_admin', '0005_event_is_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_reviewed',
        ),
        migrations.AddField(
            model_name='event',
            name='approval_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Chờ duyệt'), (2, 'Đã duyệt'), (3, 'Không duyệt')], default=2),
        ),
    ]
